'''This file is used by the parser module in order to
determine what pair a signal is referring to.
IF THE PAIR ISN'T IN THIS FILE, IT WON'T BE FOUND BY THE PARSER!'''

aliases = {
	'AUDCAD': [],
	'AUDCHF': [],
	'AUDJPY': [],
	'AUDNZD': [],
	'AUDUSD': [],
	'BTCUSD': ['bitcoin', 'btc'],
	'BGNRON': [],
	'CADCHF': [],
	'CADJPY': [],
	'CHFBGN': [],
	'CHFJPY': [],
	'CHFRON': [],
	'CHFTRY': [],
	'ETHUSD': ['ethereum', 'eth'],
	'EURAUD': [],
	'EURCAD': [],
	'EURCHF': [],
	'EURCZK': [],
	'EURDKK': [],
	'EURGBP': [],
	'EURHKD': [],
	'EURHUF': [],
	'EURILS': [],
	'EURJPY': [],
	'EURMXN': [],
	'EURNOK': [],
	'EURNZD': [],
	'EURPLN': [],
	'EURRON': [],
	'EURRUB': [],
	'EURSEK': [],
	'EURSGD': [],
	'EURTRY': [],
	'EURUSD': [],
	'EURZAR': [],
	'GBPAUD': [],
	'GBPBGN': [],
	'GBPCAD': [],
	'GBPCHF': [],
	'GBPCZK': [],
	'GBPDKK': [],
	'GBPHKD': [],
	'GBPHUF': [],
	'GBPJPY': ['gj'],
	'GBPNOK': [],
	'GBPNZD': [],
	'GBPPLN': [],
	'GBPRON': [],
	'GBPSEK': [],
	'GBPSGD': [],
	'GBPTRY': [],
	'GBPUSD': ['gu'],
	'GBPZAR': [],
	'HKDJPY': [],
	'NZDCAD': [],
	'NZDCHF': [],
	'NZDJPY': [],
	'NZDUSD': [],
	'SGDHKD': [],
	'SGDJPY': [],
	'TRYBGN': [],
	'TRYJPY': [],
	'TRYRON': [],
	'USDBGN': [],
	'USDCAD': ['USD/CAD', 'USD-CAD'],
	'USDCHF': [],
	'USDCZK': [],
	'USDDKK': [],
	'USDHKD': [],
	'USDHUF': [],
	'USDILS': [],
	'USDJPY': [],
	'USDMXN': [],
	'USDNOK': [],
	'USDPLN': [],
	'USDRON': [],
	'USDRUB': [],
	'USDSEK': [],
	'USDSGD': [],
	'USDTRY': [],
	'USDZAR': [],
	'XAUUSD': ['gold', 'xau']
}
